export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const AUTH_USER = 'AUTH_USER';

export const SIGN_OUT = 'SIGN_OUT';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_AUTH_FAILURE";

export const CREATE_LINK_SUCCESS = "CREATE_LINK_SUCCESS";
export const CREATE_LINK_FAILURE = "CREATE_LINK_FAILURE";

export const ADD_PASSWORD = "ADD_PASSWORD";
export const EDIT_DOWNLOADS = "EDIT_DOWNLOADS";

export const CLEAN_STATE = 'CLEAN_STATE';
